import { useEffect, useState } from "react";
import { History, Clock, ArrowRightLeft, Sprout, RefreshCw } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { cropSightApi } from "../services/api";
import { supabase } from "@/lib/supabase";
import UploadArea from "@/components/upload/UploadArea";
import SummaryCards from "@/components/dashboard/SummaryCards";
import MapView from "@/components/dashboard/MapView";
import { AnalyzeResponse } from "@/types/analysis";

type Scan = {
  id: string;
  timestamp: string;
  total_zones: number;
  severe_pct: number;
  healthy_pct: number;
  image_url?: string;
  overlay_url?: string;
  status?: string;
};

const HistoryPage = () => {
  const [currentFieldId, setCurrentFieldId] = useState<string | null>(null);
  
  const [history, setHistory] = useState<Scan[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [latestAnalysis, setLatestAnalysis] = useState<AnalyzeResponse | null>(null);

  const fetchRealTimeScans = async (fieldId: string) => {
    try {
      setIsLoading(true);
      const data = await cropSightApi.getHistoricalScans(fieldId);
      setHistory(data.scans || []);
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    const initField = async () => {
       const { data: { user } } = await supabase.auth.getUser();
       if (!user) return;
       
       try {
           const fieldsObj = await cropSightApi.getFields(user.id);
           let activeFieldId = fieldsObj.fields?.[0]?.id;
           
           if (!activeFieldId) {
               const newField = await cropSightApi.createField(user.id, "Main Farmland");
               activeFieldId = newField.id;
           }
           
           setCurrentFieldId(activeFieldId);
           fetchRealTimeScans(activeFieldId);
       } catch (err) {
           console.error("Failed to sync fields", err);
       }
    };
    initField();
  }, []);

  const handleAnalysisComplete = (data: AnalyzeResponse) => {
    setLatestAnalysis(data);
    toast.success("Analysis complete. Saved to database!");
    if (currentFieldId) fetchRealTimeScans(currentFieldId);
  };

  const runAnalytics = async (pastScanId: string, latestScanId: string) => {
    if (!currentFieldId) return;
    try {
      toast.loading("Analyzing temporal anomalies...", { id: "compare-toast" });
      const insights = await cropSightApi.compareScans(currentFieldId, pastScanId, latestScanId);
      
      if(insights.comparison.trend === "RECOVERY" || insights.comparison.trend === "IMPROVING") {
         toast.success(`Positive Trend: ${insights.comparison.insights[0]?.message || "Your area recovered!"}`, { id: "compare-toast" });
      } else if (insights.comparison.trend === "WORSENING" || insights.comparison.trend === "DETERIORATION") {
         toast.error(`Warning: ${insights.comparison.insights[0]?.message || "Crops are deteriorating."}`, { id: "compare-toast" });
      } else {
         toast.info("Crops have remained stable since the previous scan.", { id: "compare-toast" });
      }
    } catch (error) {
       toast.error("Comparison failed. Make sure you hooked up Supabase correctly.", { id: "compare-toast" });
    }
  };

  const openReport = async (scanId: string) => {
    toast.loading("Locating report document...", { id: "report-toast" });
    try {
      const res = await cropSightApi.getReportUrl(scanId);
      if (res.report_url) {
        toast.dismiss("report-toast");
        window.open(res.report_url, '_blank');
      } else {
        toast.info("Report is still being generated by the AI block. Check back in 10 seconds.", { id: "report-toast" });
      }
    } catch (err) {
      toast.info("Report is still being generated or unavailable.", { id: "report-toast" });
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-foreground flex items-center gap-2">
          <History className="h-6 w-6 text-primary" />
          Time-Series Analysis
        </h1>
        <p className="text-sm text-muted-foreground mt-1">Upload a scan right here to trigger active monitoring</p>
      </div>

      {!latestAnalysis && currentFieldId ? (
        <div className="max-w-2xl">
          <UploadArea onAnalysisComplete={handleAnalysisComplete} fieldId={currentFieldId} />
        </div>
      ) : latestAnalysis ? (
        <div className="space-y-4">
           <div className="flex justify-between items-center">
             <h2 className="text-lg font-semibold flex items-center gap-2"><Sprout className="w-5 h-5" /> Latest Analysis Report</h2>
             <div className="flex items-center gap-4">
                 {latestAnalysis.scan_id && (
                    <button onClick={() => openReport(latestAnalysis.scan_id!)} className="text-primary hover:underline text-sm font-medium">View Full Report</button>
                 )}
                 <button onClick={() => setLatestAnalysis(null)} className="text-muted-foreground hover:underline text-sm font-medium">Clear</button>
             </div>
           </div>
           <SummaryCards summary={latestAnalysis.summary} />
           <div className="h-[400px]">
              <MapView geo={latestAnalysis.geo} zones={latestAnalysis.zones} mapImage={latestAnalysis.map} />
           </div>
        </div>
      ) : null}

      <div className="space-y-4 pt-4">
        <h2 className="text-xl font-bold text-foreground">Chronological History</h2>
        
        {isLoading && (
          <div className="flex items-center gap-3 p-6 bg-muted/30 rounded-2xl border border-dashed border-border">
            <RefreshCw className="w-5 h-5 text-primary animate-spin" />
            <p className="text-sm text-muted-foreground font-medium">Fetching history...</p>
          </div>
        )}
        
        {!isLoading && history.length === 0 && (
          <div className="text-center p-12 bg-muted/20 rounded-2xl border border-dashed border-border">
             <History className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
             <p className="text-sm text-muted-foreground">No historical scans found yet.</p>
          </div>
        )}

        <div className="grid grid-cols-1 gap-4">
          <AnimatePresence mode="popLayout">
            {history.map((item, i) => {
              const isPending = item.status === "pending_analysis";
              
              return (
              <motion.div
                key={item.id}
                layout
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.2 }}
                className="card-elevated p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 relative z-10"
              >
            <div className="flex items-center gap-4">
              <div className="h-12 w-12 rounded-lg bg-primary/10 overflow-hidden flex-shrink-0 relative border border-border">
                {item.overlay_url || item.image_url ? (
                   <img src={item.overlay_url || item.image_url} alt="Scan thumbnail" className="h-full w-full object-cover" />
                ) : (
                   <Clock className="h-4 w-4 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                )}
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium text-foreground">{new Date(item.timestamp).toLocaleString()}</p>
                  {isPending && (
                     <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/10 text-amber-600 border border-amber-500/20">PENDING</span>
                  )}
                </div>
                {!isPending ? (
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {item.total_zones} zones · Healthy: {item.healthy_pct}% · Severe: {item.severe_pct}%
                  </p>
                ) : (
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Drone ingestion complete. Waiting for analysis.
                  </p>
                )}
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              {isPending ? (
                 <button 
                  onClick={async () => {
                     toast.loading("Analyzing drone frame...", { id: "analyze-toast" });
                     try {
                        const data = await cropSightApi.analyzeExistingScan(item.id);
                        handleAnalysisComplete(data);
                        toast.success("Analysis complete!", { id: "analyze-toast" });
                     } catch (e) {
                         toast.error("Failed to analyze scan.", { id: "analyze-toast" });
                     }
                  }}
                  className="flex items-center gap-1.5 px-4 py-2 bg-primary text-primary-foreground text-sm font-semibold rounded-lg hover:bg-primary/90 transition-colors shadow-sm"
                 >
                   <Sprout className="w-4 h-4" />
                   Analyze Frame
                 </button>
              ) : (
                 <>
                  <button 
                    onClick={() => openReport(item.id)}
                    className="flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-primary/80 transition-colors"
                  >
                    View Full Report
                  </button>

                  {i < history.length - 1 && (
                    <button 
                      onClick={async () => {
                         runAnalytics(history[i + 1].id, item.id);
                         const tempWindow = window.open('about:blank', '_blank');
                         const { data } = await supabase.auth.getSession();
                         const token = data.session?.access_token || '';
                         if (tempWindow) {
                             tempWindow.location.href = cropSightApi.getComparisonReportUrl(history[i + 1].id, item.id, token);
                         }
                      }}
                      className="flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-primary/80 transition-colors"
                    >
                      <ArrowRightLeft className="w-4 h-4" />
                      Detailed Comparison
                    </button>
                  )}
                 </>
              )}
            </div>
          </motion.div>
        )})}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};

export default HistoryPage;
